spring:
  application:
    name: smart-health-system

  # POSTGRES
  datasource:
    url: jdbc:postgresql://localhost:5432/DEVELOPMENT_smart_health_system_db
    username: root
    password: root

  # JPA
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api/v1